=== Mister-Mario/VirtualDesktop/EscritorioVirtual/xml/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.uniovi.es/rutas"
			xmlns="http://www.uniovi.es/rutas"
			elementFormDefault="qualified">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="tipo" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="medioTransporte" type="xs:string" />
				<xs:element name="duracion" type="xs:duration" />
				<xs:element name="agencia" type="xs:string" />
				<xs:element name="descripcion" type="xs:string" />
				<xs:element name="personasAdecuadas" type="xs:string" />
				<xs:element name="lugarInicio" type="xs:string" />
				<xs:element name="direccionInicio" type="xs:string" />
				<xs:element ref="coordenadas" />
				<xs:element name = "referencia" type = "xs:string" minOccurs="3" maxOccurs="unbounded"/>
				<xs:element ref="recomendacion"/>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
			<xs:attribute name="fechaInicio" type="xs:date" use="optional"/>
			<xs:attribute name="horaInicio" type="xs:time" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value = "0"/>
				<xs:maxInclusive value = "10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name = "hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="descripcion" type="xs:string" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distanciaHitoAnterior" />
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distanciaHitoAnterior">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cantidad" type ="xs:decimal"/>
			</xs:sequence>
			<xs:attribute name="unidades" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:attribute name="longitud" type="xs:decimal" use="required" />
			<xs:attribute name="latitud" type="xs:decimal" use="required" />
			<xs:attribute name="altitud" type="xs:decimal" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Mister-Mario/VirtualDesktop/EscritorioVirtual/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<rutas xmlns="http://www.uniovi.es/rutas"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es/rutas rutas.xsd">
   <ruta>
        <nombre>Túnez capital</nombre>
        <tipo>Arquitectónica</tipo>
        <medioTransporte>A pie</medioTransporte>
        <duracion>P1D</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>
            La capital tunecina, es, podríamos decir, un tercio mediterránea, un tercio europea y un tercio africana. Esta ciudad tiene algunos de los contrastes más fuertes e interesantes del norte de África.
             La mezcla de culturas e influencias es clara y un paseo por sus calles lo demuestra.
        </descripcion>
        <personasAdecuadas>Todo tipo de personas</personasAdecuadas>
        <lugarInicio>Túnez</lugarInicio>
        <direccionInicio>30 Rue Jamaa Ez Zitouna, Tunis, Túnez</direccionInicio>
        <coordenadas longitud="36.79774470644965" latitud="10.171288497323301" altitud="4"></coordenadas>
        <referencia>https://www.google.com/maps/place/Mezquita+Zitouna/@36.7955421,10.1698796,17z/data=!4m6!3m5!1s0x12fd34754f0de50d:0xd6055eb2c24a4f31!8m2!3d36.7973267!4d10.1712377!16s%2Fm%2F05f50wj?entry=ttu</referencia>
        <referencia>https://www.economiadigital.es/tendenciashoy/destinos/tunez-de-la-capital-al-desierto-en-un-roadtrip-de-10-dias_20076846_102.html</referencia>
        <referencia>https://sobretunez.com/2009/11/05/dar-ben-abdallah-el-museo-de-las-costumbres/</referencia>
        <recomendacion>8</recomendacion>
         <hito>
            <nombre>Mezquita Zitouna</nombre>
            <descripcion>Mezquita histórica e importante universidad islámica, la más antigua de Túnez, con un minarete de 43 m.</descripcion>
            <coordenadas longitud="36.79774470644965" latitud="10.171288497323301" altitud="4"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>0</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/Mezquita.jpeg</foto>
        </hito>
        <hito>
            <nombre>Palacio Dar ben Abdallah</nombre>
            <descripcion>Es el museo de las artes y el patrimonio tradicional de Túnez. Su arquitectura es uno de los ejemplos más hermosos de las construcciones del siglo XVII, ubicado en el centro de la Medina de Túnez. En su colección se muestran la herencia de los años 
            y el nombre del museo es el del antiguo dueño del palacio en el que se encuentra instalado.</descripcion>
            <coordenadas longitud="36.79444648864582" latitud="10.173785474972679" altitud="4"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>4.6</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/Dar_Ben_Abdallah.jpg</foto>
        </hito>
        <hito>
            <nombre>Le musée national du Bardo</nombre>
            <descripcion>Construido dentro de uno de los mejores palacios del país, el Museo Bardo contiene una de las mayores colecciones de mosaicos romanos del mundo,
             los cuales solían decorar las presuntuosas casas romanas que puede que visites en tu recorrido por el país.</descripcion>
            <coordenadas longitud="36.809444827906646" latitud="10.134648985557394" altitud="4"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>0.6</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/museo.png</foto>
        </hito>
    </ruta>

    <ruta>
        <nombre>Alrededores de Sfax</nombre>
        <tipo>Paisajística</tipo>
        <tipo>Arquitectónica</tipo>
        <medioTransporte>Coche y ferry</medioTransporte>
        <duracion>P1D</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>
            Ruta que combina mar y tierra recorrindo lugares historicos del pais de Túnez y sus playas.
        </descripcion>
        <personasAdecuadas>Personas en buena forma física</personasAdecuadas>
        <lugarInicio>Sfax</lugarInicio>
        <direccionInicio>Anfiteatro de El Djem</direccionInicio>
        <coordenadas longitud="35.2982756564453" latitud="10.706617336438631" altitud="35.3"></coordenadas>
        <referencia>https://www.google.com/maps/place/Anfiteatro+de+El+Djem/@35.2964865,10.7043254,17z/data=!3m1!4b1!4m6!3m5!1s0x1301fc9cdf4f5df5:0xf56c08802fb823a8!8m2!3d35.2964821!4d10.7069003!16s%2Fg%2F120rrdck?entry=ttu</referencia>
        <referencia>https://www.somoutdoors.com/lugares-donde-viajar/tunez-por-tu-cuenta/</referencia>
        <referencia>https://blog-tunez.com/otros-destinos-de-tunez/islas-kerkennah/</referencia>
        <referencia>https://en.wikipedia.org/wiki/Great_Mosque_of_Sfax</referencia>
        <recomendacion>7</recomendacion>
        <hito>
            <nombre>Anfiteatro en El Djem</nombre>
            <descripcion>El anfiteatro en El Djem fue construido por los romanos bajo las órdenes del procónsul Gordiano, quién fue proclamado emperador en Thysdrus alrededor del 238 y era principalmente utilizado para espectáculos de gladiadores y carreras de carros de pequeño formato. </descripcion>
            <coordenadas longitud="35.2982756564453" latitud="10.706617336438631" altitud="35.3"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>0</cantidad></distanciaHitoAnterior>
            <foto>multimedia/djemjpg.jpg</foto>
        </hito>
        <hito>
            <nombre>Great Mosque of Sfax</nombre>
            <descripcion>La Mezquita más importante de la ciudad de Sfax</descripcion>
            <coordenadas longitud="34.73615780480023" latitud="10.761733371909365" altitud="0"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>65</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/SfaxMosque.jpg</foto>
        </hito>
        <hito>
            <nombre>Islas Kerkennah</nombre>
            <descripcion>La sensación de pasar unos días en las islas de Kerkennah es similar a la de perderse en otras orillas del Mar Mediterráneo, ya sea en Sicilia, Cerdeña o cualquier isla griega.</descripcion>
            <coordenadas longitud="34.72991197588472" latitud="11.140731886583168" altitud="0"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>55</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/kerkennah.jpg</foto>
        </hito>
    </ruta>

    <ruta>
        <nombre>Douz</nombre>
        <tipo>Paisajística</tipo>
        <medioTransporte>A pie y camello</medioTransporte>
        <duracion>P1D</duracion>
        <agencia>sahara-tunisia</agencia>
        <descripcion>
            Ruta guiada por el desierto del Sahara
        </descripcion>
        <personasAdecuadas>Personas en buena forma física</personasAdecuadas>
        <lugarInicio>Sahara-tunisia</lugarInicio>
        <direccionInicio>Souk Douz, 4260, Túnez</direccionInicio>
        <coordenadas longitud="33.457376514557566" latitud="9.025019626580125" altitud="64"></coordenadas>
        <referencia>https://www.sahara-tunisia.com/</referencia>
        <referencia>https://es.wikipedia.org/wiki/S%C3%A1hara</referencia>
        <referencia>https://www.economiadigital.es/tendenciashoy/destinos/tunez-de-la-capital-al-desierto-en-un-roadtrip-de-10-dias_20076846_102.html</referencia>
        <referencia>https://www.google.com/maps/place/Sahara+Desert+Tunisia+%E1%83%A6/@33.4578928,9.0217406,16.75z/data=!4m15!1m8!3m7!1s0x125687f0a48f8aa3:0xf20af06731ebe68d!2zRG91eiwgVMO6bmV6!3b1!8m2!3d33.4614354!4d9.0294708!16zL20vMDQzMXo4!3m5!1s0x125687f0052ca891:0x547cf34c40e7aa1f!8m2!3d33.4571621!4d9.0250329!16s%2Fg%2F11ft2cj7zt?entry=ttu</referencia>
        <recomendacion>10</recomendacion>
        <hito>
            <nombre>Sahara Desert Tunisia ღ</nombre>
            <descripcion>Comienzo de la ruta donde se ubica la agencia turística</descripcion>
            <coordenadas longitud="33.457376514557566" latitud="9.025019626580125" altitud="64"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>6</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/compañia.png</foto>
        </hito>
        <hito>
            <nombre>La Porta del Sahara</nombre>
            <descripcion>Entrada al desierto del Sahara</descripcion>
            <coordenadas longitud="33.437107814794864" latitud="9.038192239017691" altitud="63"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>6</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/puertaSahara.jpg</foto>
        </hito>
        <hito>
            <nombre>Desierto del Sahara</nombre>
            <descripcion>El desierto del Sahara es el desierto cálido más grande del mundo, con más de 9 400 000 km2 de superficie. </descripcion>
            <coordenadas longitud="33.479258386747844" latitud="9.0708610000714013" altitud="63"></coordenadas>
            <distanciaHitoAnterior unidades="km">
                <cantidad>6</cantidad>
            </distanciaHitoAnterior>
            <foto>multimedia/deserto-sahara.jpg</foto>
        </hito>
    </ruta>
</rutas>
